#! /bin/sh

rm -f par.tmp par.log.*
trap 'rm -fr par.tmp;' 1 2 15

echo "Testing par"; echo

echo "Testing cmd in input file A"
../bin/par par.a.in
for f in par.log*; do
    LN=`wc -l $f| sed -Ee 's/([0-9]+).*/\1/'`
    if test $LN -ne 5; then
	echo "FAIL: $f should have 5 lines but has $LN" >&2
	exit 1
    fi
done
egrep -v '^(!|Ending: )' par.log.* | cut -d: -f 2 | sort > par.a.out
svn diff par.a.out >par.tmp
if test $? -ne 0; then
    echo "FAIL: svn diff par.a.out does not failed" >&2
    exit 1
fi
LN=`wc -l par.tmp | sed -Ee 's/([0-9]+).*/\1/'`
if test $LN -ne 0; then
    echo "FAIL: par.a.out does not match expected output" >&2
    exit 1
fi
rm -f par.tmp par.log.*


echo "Testing cmd in input file A with -q"
../bin/par -q par.a.in |sort -n > par.a.out
svn diff par.a.out >par.tmp
if test $? -ne 0; then
    echo "FAIL: svn diff par.a.out does not failed" >&2
    exit 1
fi
LN=`wc -l par.tmp | sed -Ee 's/([0-9]+).*/\1/'`
if test $LN -ne 0; then
    echo "FAIL: par.a.out does not match expected output" >&2
    exit 1
fi

echo "Testing cmd in input file A with -qc"
../bin/par -q -n 1 -c 'echo -n {}' par.b.in > par.b.out
svn diff par.b.out >par.tmp
if test $? -ne 0; then
    echo "FAIL: svn diff par.b.out does not failed" >&2
    exit 1
fi
LN=`wc -l par.tmp | sed -Ee 's/([0-9]+).*/\1/'`
if test $LN -ne 0; then
    echo "FAIL: par.b.out does not match expected output" >&2
    exit 1
fi

# ( to indicate that the next one is a command)
#clogin  -c "show users" hostname


rm -f par.tmp par.log.*
echo PASS
