#! /bin/sh

echo "Testing par\n"

echo "Testing cmd in input file A"
../bin/par par.a.in
for f in par.log*; do
    LN=`wc -l $f| sed -Ee 's/([0-9]+).*/\1/'`
    if test $LN -ne 5; then
	echo "FAIL: $f should have 5 lines but has $LN" >&2
	exit 1
    fi
done

echo "Testing cmd in input file A with -q"
../bin/par -q par.a.in |sort -n > par.a.out
trap 'rm -fr par.tmp;' 1 2 15
svn diff par.a.out >par.tmp
if test $? != 0; then
    echo "FAIL: svn diff par.a.out does not failed" >&2
    exit 1
fi
LN=`wc -l par.tmp`
if test $LN != 0; then
    echo "FAIL: par.a.out does not match expected output" >&2
    exit 1
fi

# ( to indicate that the next one is a command)
#clogin  -c "show users" hostname


rm -f par.log.*
echo PASS
